name: 'dbt_spotify'
version: '1.0.0'
config-version: 2

profile: 'dbt_spotify'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_spotify:
    src:
      +materialized: view
    marts:
      +materialized: table
